apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: probe-vwc.gitops.local
webhooks:
  - name: probe-vwc.gitops.local
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 5
    namespaceSelector:
      matchLabels:
        recon-f1: "true"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: Namespaced
    clientConfig:
      service:
        name: recon-webhook
        namespace: default
        path: /validate
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCekNDQWUrZ0F3SUJBZ0lVRlJmNEVZNG5Ud1Q2MXZHeEFOU3pGQW1ubXJRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0V6RVJNQThHQTFVRUF3d0ljbVZqYjI0dFkyRXdIaGNOTWpZd056RTJNRE16TVRRMVdoY05Nall3TnpFNApNRE16TVRRMVdqQVRNUkV3RHdZRFZRUUREQWh5WldOdmJpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTlkrN08yMUNDTFdkQjlZd1dFOHlZTEc5UDVZT0pDak9zMWhub2RlS3pINTdIb1EKUndNWExCVXczZVR1MTl0dC9oU3NieXBHcGtsTk9BclZvTnRxbXdHTVpKOWFqN0V4U1ZXcUg0Qm00WFZhSUkzUQpiL3grYkdNOVhwelpkSUl1SDJwRjRLSi9PdnZKZkZmWUVTZ3FJTDVvWlAyeDBvcTJOelhrZFRGUUN5eEp3RjZ1ClluRVp5TnpQeEE5UkRqSysvSk1aYmhDZW4wRGlEMTVEYitYNDY2QTE3VHRuVE1KRG92NmNheEF6cWxqYWhOdnUKdkQweUFUOFEwNGpDeHZ4RTh6OWFjdnRGYTZRdlloWldseHNwYjc1d1duK1ZZMVE3Lzd5Y2dyVVNHR0FLZ0dpWQo2SHM3R3VvU1ZFdFBQRnhnWGl0L0VRSkg4U1U1M2Z6WjNaam5kQTBDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFCkZHN2U0TUR0aHZEUnkwc2JoT0NpbTZJU2tUcFZNQjhHQTFVZEl3UVlNQmFBRkc3ZTRNRHRodkRSeTBzYmhPQ2kKbTZJU2tUcFZNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQzg5akZqUAplRmxHYzBJMlNkeDVzanl1aXZWb2JUUFRCOUdOK2VIQUowUXlLcEJDTVk3TTJhWG1NK1NzVmNYOFZZVHgrZUtGClZXV1F6VDVhbXJpS24yTW9VZ0hjYXdrQ3R3L2lvRldWMkl2Z2F3bklkZXlleUVvczZmaS9BRi9zaXVUUUxKNDIKT0diU3VLSlBNQWM4UHl1U1VyY0VmSlNLeGllaXk5U0lJUE93UG9NN09yVzVLdFhIbmJQb0lzUmMzbXdueCtlMQplNFk2RXN0RUJ1Mk1Lcis3SzRxdjMzNUM2bGdXTC9IaDlpNXlyQkdwckMxSW81S0ljS3dmOTdVVWVmL1N0Qlo0CkJHUTZDU2JsRlJ2dFUzdnpPZWo5OENnRk1hSXpZNzR6eWhFOCszRjc5Wkg5OExTemVvS2c1MVVBL0VmYkVhYjUKYnRwTnBKRVhDR1dhWkRBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
