apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: probe-vwc.gitops.local
webhooks:
  - name: probe-vwc.gitops.local
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 5
    namespaceSelector:
      matchLabels:
        recon-f1: "true"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: Namespaced
    clientConfig:
      service:
        name: recon-webhook
        namespace: default
        path: /validate
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCekNDQWUrZ0F3SUJBZ0lVU1RESVV5UEtvNFEwSjFieXJCdjRrYThmdkljd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0V6RVJNQThHQTFVRUF3d0ljbVZqYjI0dFkyRXdIaGNOTWpZd056RTJNRE15T1RRM1doY05Nall3TnpFNApNRE15T1RRM1dqQVRNUkV3RHdZRFZRUUREQWh5WldOdmJpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTXNURXJXU1RudE1CQzZ1b05YdXFQTzIxSFBneGV3RFI5bnFXYlpMcEd1Vi9aKzkKNFcxZVpRdGpnMExrWWlIOFE4SldQYkpNTG5qNVpFNm15QnlYa0kveDRmTGxaS2JtWm80cUhSN2x6Nzh6d0hRVwprbTd5bllFTGRheU4rdFlka1FJM29JeVF6RjBNTlpZaXEyRjRxcHdaZGZwKzNXYmY2Smh3cXhKbjNHazlQT3NDCllYK1g1ZlFuM3pmSWVMSVdJV0RPTXA4RlFzSDNuTndNa0tGZVpkQ1Jlc0RkZXk3RzlyYzFOczYzbm8zYXZ6S1UKeC9uR0N6WitMemZMNWx3TElaWlNKYlA2Tnp0aVU1VjE0aVprci9wQ2w0OEVtS01yYTlZdk1Oem9ZcStLYkhmWApMREc5aHRiaFFTaWU5UGw3cytabnpldWFXUTJaMThubDY3cmtxWU1DQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFCkZJcWt3M2lLQ3BFbnJ2T1NSRml1MGMwdVA3aFpNQjhHQTFVZEl3UVlNQmFBRklxa3czaUtDcEVucnZPU1JGaXUKMGMwdVA3aFpNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQVYyYzEwSgpuZkIwZ29LV3IxZjhWZUNuZjVxU1VuSER0KzRsRDNhbEMvVWQrSnlPbXVCYm1vdWFKQ3JnYzNGNm9oT0pCTFJ6CkFqNmkvTGZYb05pSlJZR0VrSkdRcEwvNGhjRlZ3bS9tc0NKRlJQV0xQUTFWdjZvSHRvNHIwWXpyZTN0TytyZkwKNVcrS1lmeW9JU2drdGc3Y1JpK3BqbG9abk55MnRRdEdPb2VteGFNTmJIMy9kaTdWdldSc2tpelQ2QmJ3RmRlbwoydUV5U0RCWjY0ZUtqTDZ1ektaV0UxM05IZVF6Q0pVUGNIK3c0eUd2VUpuL3pZRU5hdURHdzluWXo5dzh5cHdPCjJpVTJlMFdIWk80NVNXb2R0eHlKenFwZ3Zva1c0RWJIM0VBbWhuM1UvZnlXWVNISmNFV3EzSzN6SUxqYjROajYKMTZoaXRUVzQyaGEwZSswPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
