apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: probe-vwc.gitops.local
webhooks:
  - name: probe-vwc.gitops.local
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 5
    namespaceSelector:
      matchLabels:
        recon-f1: "true"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: Namespaced
    clientConfig:
      service:
        name: recon-webhook
        namespace: default
        path: /validate
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCekNDQWUrZ0F3SUJBZ0lVUldqeThBVjdHdW9xZWsrR1dEdjBBUW5JdmEwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0V6RVJNQThHQTFVRUF3d0ljbVZqYjI0dFkyRXdIaGNOTWpZd056RTJNRFF4TVRVM1doY05Nall3TnpFNApNRFF4TVRVM1dqQVRNUkV3RHdZRFZRUUREQWh5WldOdmJpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTFdENVJIR0gxaE9tMldUbmZxVWxxSi9tRkVDa3o1VlhBZ0szYWlTVC83cWpndEsKUHI4ZlI4SFpuZkhXZXBEQVY3YXFQd3dpbCtCMXRlNmhpTThRKzZqNTRmRENodmFueTRFRS81NlRrUnlsUHhCaAplUjBGampqN3c1MzFrVFprUzUrZGtFckwzZnNaUkN2V28xd0V6b0NBM2xPRVpIWVB5NWp3RDI0c0VicG5BL3FVCmhpNHR5WUcrN1FZYk0yZndvQjVYOGFDaE5UTmtPMmZLRWZtVWMxU3J3cU5QdExmZnVSc24vSlVjNU9yS1lLa3MKZ0twbmhtKzBCdThCRzNtUjJNNndPNWZEUThvT0hlQjVjemI3S29ad0MxSTM1dzM5ckd1cjVQOFpXUytrTG5rTwozcGNUYmh3RmdwcVJYUWtsaFdtcWpEZXhta2g0ZDIxOWxWL0hScThDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFCkZGRll4dm11d1JZS3lEVWxmMExuclpDQUhCNGxNQjhHQTFVZEl3UVlNQmFBRkZGWXh2bXV3UllLeURVbGYwTG4KclpDQUhCNGxNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSDcrTERKdwpHMEkrRTNDSThoMEkzT0xRdlBFbVpiajJFVlRUS2hCNXl1QlJPRm9mbSs1Z0VHR1JKS0VMVCtaTkxibS9WdTV1CkNmb2FTeUxIK1c1MVJId0xSbkR0RjRXSHY3bStDS2M1ckMrSXN0ZkpiY3hFVEZpMlJiOFlPVUE1WmNHYlptR2sKYlVJb3loWjBpbDZnczFFemQvRzhjVERhY1VXTzFHOWJYSmFRdTZENkZwTHhSZUJmM1UwdEFFem1TeE9CbkJMNgpYNDc0M283dFczdHdteDZsdFlVMDJxd0NuTy9CUDcvM0p1ZWZnT1dES3FoKzJ3UVVlYVA3S2NBcUdKVkV4RC81CkhIZFJRb3hGaE84c0FTTzE4ZmhaQmxNU3hOS1dNWHNtUm5saVRHMlE3ZXZLUnpqWDdxSXVsN1RKS2t1TWovRmIKUWxGWTZYSjJtMUhPMEtNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
